relo,./conf/relo/feldmoching/abasto.conf,0630,0700
trav,./conf/trav/feldmoching/abasto_cog.conf,0701,0710
relo,./conf/relo/muenchen_arbeit/cog.conf,0701,1830
trav,./conf/trav/feldmoching/cog_abasto.conf,1831,1840
relo,./conf/relo/feldmoching/abasto.conf,1832,1915
trav,./conf/trav/feldmoching/abasto_el_greco.conf,1916,1925
relo,./conf/relo/feldmoching/el_greco.conf,1926,2130
trav,./conf/trav/feldmoching/el_greco_abasto.conf,2131,2140
relo,./conf/relo/feldmoching/abasto.conf,2132,2200
end