relo,./conf/relo/feldmoching/abasto.conf,0630,0700
trav,./conf/trav/feldmoching/abasto_cog.conf,0701,0710
relo,./conf/relo/muenchen_arbeit/cog.conf,0701,0710
trav,./conf/trav/feldmoching/cog_abasto.conf,0711,0715
relo,./conf/relo/feldmoching/abasto.conf,0712,0717
trav,./conf/trav/feldmoching/abasto_contadino.conf,0718,0719
relo,./conf/relo/feldmoching/contadino.conf,0719,0723
trav,./conf/trav/feldmoching/contadino_abasto.conf,0724,0725
relo,./conf/relo/feldmoching/abasto.conf,0725,0728
end