relo,./conf/relo/feldmoching/abasto.conf,2358,0700
relo,./conf/relo/muenchen_arbeit/cog.conf,0659,0710
relo,./conf/relo/feldmoching/abasto.conf,0709,0717
relo,./conf/relo/feldmoching/contadino.conf,0716,0723
relo,./conf/relo/feldmoching/abasto.conf,0722,2359
end