relo,./conf/relo/feldmoching/abasto.conf,2357,0700
relo,./conf/relo/muenchen_arbeit/cog.conf,0659,1830
relo,./conf/relo/feldmoching/abasto.conf,1829,1915
relo,./conf/relo/feldmoching/contadino.conf,1914,2100
relo,./conf/relo/feldmoching/abasto.conf,2059,2359
end